#!/usr/local/bin/perl -w
#
# Create compile values from a given Makefile
#
# contact: m.a.hermanns@fz-juelich.de
#
####################################################################

use strict;

my ($line,$n);

open(IN,$ARGV[0]);

while(<IN>)
{
    $line = $_;
    $n = $line =~ s/^([A-Z0-9a-z_]+)\s*=\s*([a-zA-Z0-9_\-].*[a-zA-Z0-9_\-])[\ ]*/<sub from=\"\#$1\#\" to=\"$2\" \/>/m;
    if ($n) { print $line; }
}

close(IN);
